# Generated by Django 3.1 on 2020-08-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_profile1_profile2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
            ],
        ),
    ]
